#!/bin/bash
# Simple Script for counting down
date1=$((`date +%s` + $1)); 
while [ "$date1" -ge `date +%s` ]; do  
  echo -ne "$(date -u --date @$(($date1 - `date +%s`)) +%H:%M:%S)\r" 
  sleep 0.1 
done
espeak -s 150 "Countdown Complete!";
