#!/bin/bash
suffix(){
  case $(date +%_d) in
    1|21|31) echo "st";;
    2|22)    echo "nd";;
    3|23)    echo "rd";;
    *)       echo "th";;
  esac
}
color1=F9C823
color2=FB8C49
color3=FC506E


echo -n    %{F#$color1}$(date "+ %I:%M") %{F#}$(date "+%p") %{F#$color2}$(date "+ %A")%{F#}, the $(date "+%-d$(suffix) of") \
%{F#$color3}$(date "+%B %Y")
